---
title: "Nurses"
author: "Gary Lu"
date: "10/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)

nurses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-10-05/nurses.csv')
```

```{r}
ordered_nurses <- 
nurses %>% 
  group_by(State, Year) %>% 
  arrange(desc(`Total Employed RN`), .by_group = TRUE) %>% 
  ungroup(Year) %>% 
  mutate(delta = coalesce(`Total Employed RN` - lag(`Total Employed RN`)),
         p_delta = (delta / `Total Employed RN`) * 100,
         p_delta = round(p_delta, 2)) %>% 
  ungroup()

ordered_nurses %>% 
  select(State, Year, `Total Employed RN`, delta, p_delta)
```

```{r}
# Employment over the years
ordered_nurses %>% 
  filter(Year >= 2020) %>% 
  group_by(State) %>% 
  summarise(delta = delta) %>% 
  arrange(desc(delta)) %>% 
  head(10) %>% 
  ggplot(aes(x = fct_reorder(State, delta), y = delta))+
  geom_col()+
  coord_flip()+
  labs(title = "Top 10 states with highest average number of new nurses 2019-2020",
       x = "",
       y = "New hires")
```

```{r}
ordered_nurses %>% 
  unite(State:Year, sep = ", ", col = State_Year) %>% 
  arrange(desc(`Hourly Wage Median`)) %>% 
  head(10) %>% 
  ggplot(aes(x = fct_reorder(State_Year, `Hourly Wage Median`), y = `Hourly Wage Median`))+
  geom_col()+
  coord_flip()+
  labs(title = "Top 10 Hourly Median Wages",
       x = "",
       y = "Hourly Median Wage")
```

Makes sense considering the cost of living in these states

```{r, Growth of Median wages}
ordered_nurses %>% 
  group_by(State) %>%
  filter(!is.na(`Hourly Wage Median`)) %>% 
  mutate(HWM_diff = coalesce(`Hourly Wage Median` - lag(`Hourly Wage Median`))) %>% 
  summarise(total_HMW_diff = last(`Hourly Wage Median`) - first(`Hourly Wage Median`))

# Using California as an example since it has the highest median wage for nurses,

ca_nurses <- ordered_nurses %>% filter(State == "California")
ca_model <- lm(`Hourly Wage Median` ~ Year, data = ca_nurses)
ca_loess <- loess(`Hourly Wage Median` ~ Year, data = ca_nurses)
ca_nurses <- ca_nurses %>% add_residuals(ca_loess)



ca_nurses %>% select(Year, `Hourly Wage Median`) %>% 
  add_predictions(ca_model) %>% 
  ggplot(aes(x = Year, y = `Hourly Wage Median`))+
  geom_line()+
  geom_line(aes(y = pred), color = "red")

ca_nurses %>% select(Year, `Hourly Wage Median`) %>% 
  add_predictions(ca_loess) %>% 
  ggplot(aes(x = Year, y = `Hourly Wage Median`))+
  geom_line()+
  geom_line(aes(y = pred), color = "blue")

```

```{r}
# Relationship between # of nurses and pay
rbnp <- ordered_nurses %>% select(State, Year, `Total Employed RN`, `Hourly Wage Median`)

rbnp %>% 
  group_by(State) %>% 
  mutate(rn_delta = `Total Employed RN` - lag(`Total Employed RN`),
         wage_delta = `Hourly Wage Median` - lag(`Hourly Wage Median`)) %>% 
  filter(!is.na(rn_delta) & !is.na(wage_delta)) %>% 
  filter(State %in% c("Massachusetts")) %>% 
  ggplot(aes(x = Year, y = wage_delta))+
  geom_line()+
  labs(y = "Wage increase")

rbnp %>% 
  group_by(State) %>% 
  mutate(rn_delta = `Total Employed RN` - lag(`Total Employed RN`),
         wage_delta = `Hourly Wage Median` - lag(`Hourly Wage Median`)) %>% 
  filter(!is.na(rn_delta) & !is.na(wage_delta)) %>% 
  filter(State %in% c("Massachusetts")) %>% 
  ggplot(aes(x = Year, y = rn_delta))+
  geom_line()+
  labs(y = "RN increase")

# Grouping by year
rbnp %>% 
  group_by(Year) %>% 
  filter(!is.na(`Total Employed RN`)) %>% 
  filter(!is.na(`Hourly Wage Median`)) %>% 
  summarise(National_Employed_RN = sum(`Total Employed RN`),
         National_Median_Wage = median(`Hourly Wage Median`)) %>% 
  mutate(delta_rn = National_Employed_RN - lag(National_Employed_RN),
         delta_wage = National_Median_Wage - lag(National_Median_Wage),
         pct_rn = delta_rn / National_Employed_RN * 100,
         pct_wage = delta_wage / National_Median_Wage * 100) %>%
  ggplot(aes(x = Year))+
  geom_line(aes(y = pct_rn), color = "blue")+
  geom_line(aes(y = pct_wage), color = "red")+
  labs(title = "Percent changes in national median wages and total employed RN in nation",
       y = "Percent change")
  
```

